#%RAML 1.0 NamedExample
value:

  - 
    id: 1 
    empid: 116472
    name: Prateek
    email: prateek.dhal@publicissapient.com
    destination: SAL2
    nationality: Indian
    age: 34
	
  - 
    id: 2 
    empid: 10021
    name: Rohan
    email: rohan.raj@publicissapient.com
    destination: Manager Technology
    nationality: Indian
    age: 37